Chat/urls.py
from django.urls import path
from Chat import views

urlpatterns = [
    path('', views.chat_list_page),
    path('<str:room_name>/', views.chat_page, name='room'),
]

TravellApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from Authentication.views import ajax_load_countries
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('UserProfile.urls')),
    path('reg/', include('Authentication.urls')),
    path('chat/', include('Chat.urls')),
    path('house/', include('HouseSearch.urls')),

    path('load_countries/', ajax_load_countries, name='load_countries'),
  ]


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + staticfiles_urlpatterns()

UserProfile/urls.py
from django.urls import path
from UserProfile import views

urlpatterns = [

    path('note/create/', views.note_create_page, name='note_create'),
    path('note/delete/', views.delete_note, name='note_delete'),
    path('note/edit/<slug:note_id>/', views.note_edit_page, name='note_edit'),
    path('note/<slug:note_id>/', views.note_page, name='note'),
    path('<slug:user_id>/load_notes/', views.load_notes, name='load_notes'),
    path('<slug:user_id>/', views.home, name='home'),

]


""" path('<slug:user_name>', views.home),
   path('login', views.login),
   path('logout', views.logout),
   path('registrations', views.registr),
"""

UserProfile/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from model_utils import Choices
from Lib import FFD


class UserExt(User):
    class Meta:
        proxy = True

    def get_new_note_portion(self, since=None, limit=10):
        qs = self.note_set.order_by('-date_public')
        if since:
            qs = qs.filter(date_public__lte=since)
        qs = qs[0:limit]
        return qs

    def get_absolute_url(self):
        return reverse('home', args=[str(self.id)])


class Country(models.Model):
    name = models.CharField(max_length=30)
    phone_code = models.CharField(max_length=4)

    def __str__(self):
        return self.name

class UserInfo(models.Model):

    TRAVEL = 'TR'
    SEARCH = 'SH'
    RENT_HOUSE = 'HH'
    STATUS_TYPE = Choices(
        (TRAVEL, 'Travelling'),
        (SEARCH, 'Find house'),
        (RENT_HOUSE, 'Rent a house'),
    )

    user = models.OneToOneField(User,
                                unique=True,
                                on_delete='Cascade')
    gender = models.BooleanField(default=False)
    birthday = models.DateField(blank=True)
    status = models.CharField(max_length=2,
                              choices=STATUS_TYPE,
                              blank=True,
                              default=TRAVEL)

    phone_num = models.CharField(max_length=12,
                                 blank=True)
    country = models.ForeignKey(Country, on_delete='Cascade', null=True)
    city = models.CharField(max_length=30,
                            blank=True)
    info = models.TextField(max_length=256,
                            blank=True)

    registration = models.DateField(auto_now_add=True)
    last_visit = models.DateTimeField(auto_now=True)
    big_photo = models.ImageField(upload_to='user_photo/',
                                  blank=True,
                                  default='def_user_photo.png')


class NoteManager(models.Manager):

    def get_queryset(self):
        return super(NoteManager, self).get_queryset().filter(deleted__isnull=True)


class NoteDeleteManager(models.Manager):

    def get_queryset(self):
        return super(NoteDeleteManager, self).get_queryset().filter(deleted__isnull=False).order_by('-deleted')


class Note(models.Model):

    user = models.ForeignKey(User, on_delete='Cascade')
    text = models.TextField(max_length=1000, blank=True)
    date_public = models.DateTimeField(auto_now_add=True)

    deleted = models.DateField(null=True, db_index=True)

    # note_objects = NoteManager()
    objects = NoteManager()
    note_delete_objects = NoteDeleteManager()

    def get_absolute_url(self):
        return reverse('note', args=[str(self.id)])

    def get_images(self):
        return self.attachment_set.filter(type=FFD.IMAGE)

    def get_video(self):
        return self.attachment_set.filter(type=FFD.VIDEO)

    def get_audio(self):
        return self.attachment_set.filter(type=FFD.AUDIO)

    def get_files(self):
        return self.attachment_set.filter(type=FFD.FILES)


def get_upload_file_way(ftype):
    return 'user_files/%s/' % ftype


class Attachment(models.Model):

    note = models.ForeignKey(Note, on_delete='Cascade')
    type = models.CharField(max_length=2,
                            choices=FFD.FILE_TYPE)
    file = models.FileField(upload_to='user_files/all_files/',
                            blank=True)


def save_attach(files_dict, note):
    files = files_dict.getlist('images', None)
    for file in files:
        new_attachment = Attachment(note=note, file=file, type='IM')
        new_attachment.save()

    files = files_dict.getlist('video', None)
    for file in files:
        new_attachment = Attachment(note=note, file=file, type='VD')
        new_attachment.save()

    files = files_dict.getlist('audio', None)
    for file in files:
        new_attachment = Attachment(note=note, file=file, type='AU')
        new_attachment.save()

    files = files_dict.getlist('files', None)
    for file in files:
        new_attachment = Attachment(note=note, file=file, type='FL')
        new_attachment.save()

UserProfile/forms.py
from django import forms

from UserProfile.models import *


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        exclude = ['user', 'date_public', 'deleted']

        widgets = {
            'text': forms.Textarea(attrs={'name': 'text',
                                          'id': 'id_text',
                                          'maxlength': 1000,
                                          'class': 'form-control h-100',
                                          'rows': False,
                                          'cols': False,
                                          'style': False,
                                          }),
        }


class AttachmentForm(forms.Form):
    images = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'name': 'photo',
                                      'multiple': True,
                                      'class': 'file invisible position-absolute',
                                      'required': False,
                                      'accept': 'image/*'})
    )

    video = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'name': 'video',
                                      'multiple': True,
                                      'class': 'file invisible position-absolute',
                                      'required': False,
                                      'accept': 'video/*'})
    )

    audio = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'name': 'audio',
                                      'multiple': True,
                                      'class': 'file invisible position-absolute',
                                      'required': False,
                                      'accept': 'audio/*'})
    )

    files = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'name': 'files',
                                      'class': 'file invisible position-absolute',

                                      'required': False,
                                      'multiple': True,
                                      })
    )

UserProfile/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404, JsonResponse, QueryDict, HttpRequest
from django.template.loader import render_to_string

from UserProfile.forms import *
from UserProfile.models import UserExt, save_attach

from datetime import datetime

from Lib.FileFormats import handle_uploaded_file



# Create your views here.


def home(request, user_id):
    user = get_object_or_404(UserExt, pk=user_id)

    try:
        user_info = UserInfo.objects.get(pk=user.pk)
    except UserInfo.DoesNotExist:
        user_info = None

    status = 'none'
    if user_info:
        status = user.userinfo.STATUS_TYPE[request.user.userinfo.status]

    notes = user.get_new_note_portion()


    data = {
        'user': user,
        'status': status,
        'is_owner': False,
        'notes': notes,
            }

    if user_id == request.user.pk:
        data['is_owner'] = True

    return render(request, "UserProfile/home.html", data)


def load_notes(request, user_id):
    user = get_object_or_404(UserExt, pk=user_id)
    if request.is_ajax():

        since = None
        if 'since' in request.GET:
            since = datetime.strptime(request.GET['since'], '%d-%m-%Y %H:%M')

        notes = user.get_new_note_portion(since)

        data = {
            'notes': notes,
        }
        page = render_to_string('UserProfile/notes_list.html', data)
        response = {'html': page}
        return JsonResponse(response)

    return Http404


@login_required
def note_page(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    is_owner = (request.user == note.user)
    data = {
        'note': note,
        'is_owner': is_owner,

    }
    return render(request, 'UserProfile/note_page.html', data)


@login_required
def note_create_page(request):
    user = UserExt.objects.get(pk=request.user.pk)
    errors_file_type = []

    if request.method == 'POST':
        form_note = NoteForm(request.POST)
        form_attach = AttachmentForm(request.POST, request.FILES)

        if form_note.is_valid():

            errors_file_type = (handle_uploaded_file(request.FILES))
            if not len(form_note.cleaned_data['text']) and not (len(request.FILES)):
                errors_file_type.append('Empty post!')



            if not errors_file_type:
                print('q')
                new_note = form_note.save(commit=False)
                new_note.user = user
                new_note.save()

                save_attach(request.FILES, new_note)

                if request.is_ajax():
                    dict = []
                    for im in new_note.get_images():
                        a = {}
                        a['image']: im.file.url
                        dict.append(a)

                    return render(request,
                                  'UserProfile/note_block.html',
                                  {'note': new_note,
                                   'is_creating': True,
                                   })

                return HttpResponseRedirect('/user/%s/' % request.user.pk)

            else:

                return JsonResponse({'errors': errors_file_type})

    else:
        form_note = NoteForm()
        form_attach = AttachmentForm()


    return render(request,
                  'UserProfile/includes/create_note.html',
                  {'form_note': form_note,
                   'form_attach': form_attach,
                   'is_creating': True,
                   'errors_type': errors_file_type,
                   })


@login_required
def note_edit_page(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    if request.user != note.user:
        return Http404

    if request.method == 'POST':
        form_note = NoteForm(request.POST)
        if form_note.is_valid():
            note.text = form_note.cleaned_data['text']
            note.save()
            if request.is_ajax():
                return JsonResponse({'text': note.text,
                                     'status': 'success'})
            return HttpResponseRedirect('/user/%s/' % request.user.pk)
        else:
            if request.is_ajax():
                return JsonResponse({'text': note.text,
                                     'status': 'fail'})
    else:
        form_note = NoteForm(instance=note)

    data = {'form_note': form_note,
            'note': note,
            }
    if request.is_ajax():
        template = 'UserProfile/create_edit_note_block.html'
    else:
        template = 'UserProfile/edit_note.html'
    return render(request, template, data)


def delete_note(request):
    if request.method == 'POST':
        note = Note.objects.get(pk=int(QueryDict(request.body).get('notepk')))
        if request.user == note.user:
            note.deleted = datetime.now()
            note.save()
            response_data = {}
            response_data['msg'] = 'Post was deleted.'
            return JsonResponse(response_data)

    return JsonResponse({"msg": "this isn't happening"})

templates/UserProfile/includes/create_note.html
<form action="/user/note/create/" enctype="multipart/form-data" method="post"
      class="form-post-add row d-flex justify-content-end">
    {% csrf_token %}

    <h5 class="col-12 ml-2">New note</h5>

    <div class="col-9 pr-1">
        <!--поле форми NoteForm-->
        {{ form_note.text }}
    </div>

    <div class="col-3 pl-1">

        <input class="btn btn-primary mb-2 w-100" type="submit" value="Post"/>

        <div class="btn-group w-100">

            <button class="btn btn-primary btn-sm dropdown-toggle w-100" type="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-plus"></i>
                Add file
            </button>

            <div class="dropdown-menu p-0">
                <!-- Image -->
                <div class="file-upload">
                    <!--поле форми AttachmentForm-->
                    {{ form_attach.images }}
                    {{ form_attach.images_file }}
                    <!--<input class="file invisible position-absolute" type="file" accept="image/*" id="id_images"
                                multiple>
                -->
                    <label class="m-0 pl-3 bg-primary" for="id_images">Image</label>
                </div>
                <!-- Video -->
                <div class="file-upload">
                    <!--<input class="file invisible position-absolute" type="file" accept="video/*" id="id_video" multiple>
                    -->
                    <!--поле форми AttachmentForm-->
                    {{ form_attach.video }}
                    {{ form_attach.video_file }}
                    <label class="m-0 pl-3 bg-primary" for="id_video">Video</label>
                </div>
                <!-- Audio -->
                <div class="file-upload">

                    <!--поле форми AttachmentForm-->
                    {{ form_attach.audio }}
                    {{ form_attach.audio_file }}

                    <!--
                    <input class="file invisible position-absolute" type="file" accept="audio/*" id="id_audio" multiple>
                    -->
                    <label class="m-0 pl-3 bg-primary" for="id_audio">Audio</label>

                </div>
                <!-- File -->
                <div class="file-upload">
                    <!--поле форми AttachmentForm-->
                    {{ form_attach.files }}
                    {{ form_attach.files_file }}
                    <!--
                    <input class="file invisible position-absolute" type="file" id="id_files" multiple>
                    -->
                    <label class="m-0 pl-3 bg-primary" for="id_files">Another file</label>
                </div>
            </div>
        </div>
        <div>
            <label class="file-label file-list-image w-100 m-0"></label>
            <label class="file-label file-list-video w-100 m-0"></label>
            <label class="file-label file-list-audio w-100 m-0"></label>
            <label class="file-label file-list-file w-100 m-0"></label>
        </div>
    </div>


    {% for error in errors_type %}
        {{ error }} <br/>
    {% endfor %}

</form>

templates/UserProfile/includes/notes_list.html
{% if notes %}

    {% for note in notes %}
        {% include "UserProfile/note_block.html" %}
    {% endfor %}

{% else %}
    "You have any note yet"
{% endif %}

templates/UserProfile/includes/userInfo.html
{% block content %}

    <!-- Information block -->
    <div class="information-block">
        <h5 class="block block-header">Information</h5>
        <div class="block block-footer">

            {% if user.userinfo.status %}
                <p><i class="fas fa-user-tag"></i> Status: {{ user.userinfo.get_status_display }} </p>
            {% endif %}

            {% if user.userinfo.country %}
                <p>
                    <!-- Такая каша для корректного вывода запятой -->
                    <i class="fas fa-map-marker-alt"></i> {{ user.userinfo.country }}{% if user.userinfo.city %},
                    {{ user.userinfo.city }}
                {% endif %}
                </p>
            {% endif %}

            {% if user.userinfo.birthday %}
                <p><i class="fas fa-user"></i> Birthday: {{ user.userinfo.birthday }}</p>
            {% endif %}

            {% if user.userinfo.phone_num %}
                <p><i class="fas fa-phone-square"></i> {{ user.userinfo.phone_num }}</p>
            {% endif %}

        </div>
    </div>

    {% if user.userinfo.info %}
        {% include "UserProfile/includes/userStatus.html" %}
    {% endif %}

{% endblock %}

templates/UserProfile/includes/userNameAvatar.html
{% block content %}

    <!-- Name -->
    <h3 class="name px-2 m-0 p-0">
        <strong>{{ user.first_name }} {{ user.last_name }}</strong>
    </h3>

    <p class="text-muted name px-2">@{{ user.username }}</p>

    <!-- Avatar -->
    <div class="avatar">
        {% if user.userinfo.big_photo %}
            <img src="{{ user.userinfo.big_photo.url }}" class="img-fluid">
        {% else %}
            {% load staticfiles %}
            <img src="{% static 'images/DefaultAvatar.png' %}" class="img-fluid">
        {% endif %}
    </div>

{% endblock %}

templates/UserProfile/includes/userStatus.html
{% block content %}

    <!-- Status block -->
    <div class="status">
        <h5 class="block block-header">Status</h5>
        <p class="block block-footer">
            {{ user.userinfo.info }}
        <p>
    </div>

{% endblock %}