Chat/urls.py
from django.urls import path
from Chat import views

urlpatterns = [
    path('', views.chat_list_page),
    path('<str:room_name>/', views.chat_page, name='room'),
]

HouseSearch/urls.py
from django.urls import path
from HouseSearch import views

urlpatterns = [
    path('', views.house_search_page, name='search_house'),
    path('create/', views.house_add_page, name='add_house'),
    path('delete/', views.house_delete, name='delete_house'),
    path('edit/<slug:house_id>/', views.house_edit_page, name='edit_house'),
    path('<slug:house_id>/', views.house_page, name='house'),

]

""" path('<slug:user_name>', views.home),
   path('login', views.login),
   path('logout', views.logout),
   path('registrations', views.registr),
"""

TravellApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from Authentication.views import ajax_load_countries
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('UserProfile.urls')),
    path('reg/', include('Authentication.urls')),
    path('chat/', include('Chat.urls')),
    path('house/', include('HouseSearch.urls')),

    path('load_countries/', ajax_load_countries, name='load_countries'),
  ]


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + staticfiles_urlpatterns()

HouseSearch/models.py
from django.db import models
from django.contrib.auth.models import User
from model_utils import Choices
from UserProfile.models import Country

from django.urls import reverse


def get_sentinel_country():
    return Country.objects.get_or_create(name='deleted')[0]


class HouseManager(models.Manager):

    def get_queryset(self):
        return super(HouseManager, self).get_queryset().filter(deleted__isnull=True)

    def multi_search(self, houses, kwargs):

        if 'min_price' in kwargs:
            houses = houses.filter(price__gt=kwargs['min_price'])
        if 'max_price' in kwargs:
            houses = houses.filter(price__lt=kwargs['max_price'])
        if 'country' in kwargs:
            country_id = Country.objects.get(name=kwargs['country']);
            houses = houses.filter(country=country_id)
        if 'type' in kwargs:
            print(kwargs['type'])
            for type in House.HOUSE_TYPE:
                if not (type[0] in kwargs['type']):
                    houses = houses.exclude(type=type[0])

        if 'city' in kwargs:
            houses = houses.filter(city=kwargs['city'])
        if 'rooms' in kwargs:
            houses = houses.filter(rooms=kwargs['rooms'])
        if 'sleeper' in kwargs:
            houses = houses.filter(sleeper=kwargs['sleeper'])
        if 'public' in kwargs:
            houses = houses.filter(date_public__gt=kwargs['public'])
        if 'active' in kwargs:
            if kwargs['active']:
                houses = houses.filter(activity=True)

        return houses


class HouseDeleteManager(models.Manager):

    def get_queryset(self):
        return super(HouseDeleteManager, self).get_queryset().filter(deleted__isnull=False).order_by('-deleted')


MAX_USER_HOUSES = 10
MAX_PRICE = 999.99
MAX_ROOMS = 50
MAX_SLEEPER = 100

class House(models.Model):

    PRIVATE_HOUSE = 'PH'
    APARTMENT = 'AP'
    VILLA = 'VL'

    HOUSE_TYPE = Choices(
        (PRIVATE_HOUSE, 'Private house'),
        (APARTMENT, 'Apartment'),
        (VILLA, 'Villa'),
    )
    """Owner user"""
    owner = models.ForeignKey(User, on_delete='Cascade')

    title = models.CharField(max_length=100, blank=True)

    """Piece of address"""
    country = models.ForeignKey(Country, on_delete=models.SET(get_sentinel_country))
    city = models.CharField(max_length=40)
    address = models.CharField(max_length=100)

    """Describe house"""
    type = models.CharField(max_length=2, choices=HOUSE_TYPE, default=PRIVATE_HOUSE)
    rooms = models.SmallIntegerField(default=1)
    sleeper = models.SmallIntegerField(default=1)
    about = models.TextField(max_length=500)

    price = models.DecimalField(decimal_places=2, max_digits=10)

    activity = models.BooleanField(default=True)
    date_public = models.DateField(auto_now_add=True)
    deleted = models.DateField(null=True, blank=True, db_index=True)

    objects = HouseManager()
    house_delete_objects = HouseDeleteManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('house', args=[str(self.id)])

    def get_images(self):
        return self.housephoto_set.all()

    def main_image(self):
        main_image = self.housephoto_set.first()
        if main_image:
            return main_image.image.url
        return None


class HousePhoto(models.Model):
    house = models.ForeignKey(House, on_delete='Cascade')
    image = models.ImageField(upload_to='house_data/photo/', blank=True)

    def __str__(self):
        return self.image.path

HouseSearch/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404, JsonResponse, QueryDict, HttpRequest
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from UserProfile.models import UserExt, Country
from .models import House, HousePhoto, MAX_USER_HOUSES
from .form import HouseForm, PhotoForm, SearchHousesForm
from datetime import datetime
from Lib import FileFormats


def user_houses(request):
    if 'user' in request.GET:
        user = get_object_or_404(UserExt, id=request.GET['user'])
        houses = House.objects.filter(owner=user)


def house_search_page(request):
    houses = House.objects.all()

    form_search = SearchHousesForm(request.GET)

    if form_search.is_valid():
        dict = form_search.get_only_full()
        if len(dict):
            houses = House.objects.multi_search(houses, dict)

    if houses:
        message = "Result: " + str(houses.count())

        paginator = Paginator(houses, 2)
        page = int(request.GET.get('page'))

        try:
            houses_page = paginator.page(page)
        except PageNotAnInteger:
            houses_page = paginator.page(1)
        except EmptyPage:
            houses_page = paginator.page(paginator.num_pages)

        return render(request, 'HouseSerch/house_search.html',
                      {'houses': houses_page,
                       'page': houses_page,
                       'form_search': form_search,
                       'message': message,
                       })
    else:
        message = "No result :("
    return render(request, 'HouseSerch/house_search.html',
                  {'houses': houses,
                   'form_search': form_search,
                   'message': message, })


def house_page(request, house_id):
    house = get_object_or_404(House, id=house_id)
    is_owner = (request.user == house.owner)
    type = house.HOUSE_TYPE[house.type]
    data = {
        'type': type,
        'house': house,
        'is_owner': is_owner,

    }
    return render(request, 'HouseSerch/house_page.html', data)


def house_add_page(request):
    user = UserExt.objects.get(pk=request.user.pk)

    if user.house_set.count() == MAX_USER_HOUSES:
        return render(request, 'HouseSerch/limit_house.html', {user: user})

    errors_file_type = []

    if request.method == 'POST':
        form_house = HouseForm(request.POST)
        form_photo = PhotoForm(request.POST, request.FILES)
        if form_house.is_valid() and form_photo.is_valid():
            errors_file_type = FileFormats.handle_uploaded_file(request.FILES)
            if not errors_file_type:
                new_house = _home_save(request, form_house, user)
                return HttpResponseRedirect('/house/%s/' % new_house.id)
    else:
        form_house = HouseForm()
        form_photo = PhotoForm()

    return render(request,
                  'HouseSerch/add_house.html',
                  {'form_house': form_house,
                   'form_photo': form_photo,
                   'is_creating': True,
                   'errors_type': errors_file_type,
                   })


def _home_save(request, form_house, user):
    new_house = form_house.save(user)
    files = request.FILES.getlist('image', None)
    for file in files:
        new_house_photo = HousePhoto(house=new_house, image=file)
        new_house_photo.save()
    return new_house


def house_edit_page(request, house_id):
    house = get_object_or_404(House, id=house_id)
    user = UserExt.objects.get(pk=request.user.pk)

    if user != house.owner:
        return Http404

    errors_file_type = []
    if request.method == 'POST':
        form_house = HouseForm(request.POST, instance=house)
        form_photo = PhotoForm(request.POST, request.FILES)
        if form_house.is_valid() and form_photo.is_valid():
            errors_file_type = FileFormats.handle_uploaded_file(request.FILES)
            if not errors_file_type:
                new_house = _home_save(request, form_house, user)
                return HttpResponseRedirect('/house/%s/' % new_house.id)
    else:
        form_house = HouseForm(instance=house)
        form_photo = PhotoForm()

    return render(request,
                  'HouseSerch/add_house.html',
                  {'form_house': form_house,
                   'form_photo': form_photo,
                   'house': house,
                   'errors_type': errors_file_type,
                   })


def house_delete(request):
    if request.method == 'POST':
        house = House.objects.get(pk=int(QueryDict(request.body).get('housepk')))
        if request.user == house.owner:
            house.deleted = datetime.now()
            house.save()
            response_data = {}
            response_data['msg'] = 'Post was deleted.'
            return JsonResponse(response_data)

    return JsonResponse({"msg": "this isn't happening"})

templates/HouseSerch/add_house.html
{% extends "base.html" %}

{% block title %}{{ user.username }} | House{% endblock %}

{% block content %}

<div class="row justify-content-center">
	{% include 'HouseSerch/create_edit_house_block.html' %}
</div>

{% endblock %}

templates/HouseSerch/create_edit_house_block.html
<form class="house-form form-group col-8" enctype="multipart/form-data" method="post">
    {% csrf_token %}

    <div class="house-edit-header block block-header">
        <h4 class="pl-3 mb-1">House edit</h4>
    </div> <!-- house-edit-header -->

    <div class="house-edit-body block p-3">

        <label class="pl-2 mb-0" for="id_title">Title</label>
        {{ form_house.title }}

        <div class="row">
            <div class="col-6">
                <label class="pl-2 mb-0" ="id_country">Country</label>
                {{ form_house.country }}
            </div>
            <div class="col-6">
                <label class="pl-2 mb-0" for="id_city">City</label>
                {{ form_house.city }}
            </div>
        </div>

        <label class="pl-2 mb-0" for="id_address">Address</label>
        {{ form_house.address }}

        <div class="row">
            <div class="col-4">
                <label class="pl-2 mb-0" for="id_type">Type of house</label>
                {{ form_house.type }}
            </div>
            <div class="col-4">
                <label class="pl-2 mb-0"for="id_rooms">Rooms</label>
                {{ form_house.rooms }}
            </div>
            <div class="col-4">
                <label class="pl- mb-0" for="id_sleeper">Sleeper place</label>
                {{ form_house.sleeper }}
            </div>
        </div>

        <label class="pl-2 mb-0" for="id_price">Price</label>
        {{ form_house.price }}

        <label class="pl-2 mb-0" for="id_about">About</label>
        {{ form_house.about }}
        
        <div class="file-upload col-3">
            {{ form_photo.image }}
            {{ form_photo.image_file }}
            <label class="btn m-0 btn-warning" for="id_image">Set images</label>
        </div>

        <div id="house-images-board" class="col-9">
            {% if is_creating == false %}
                {% for image in house.get_images %}
                    <img src="{{ image.image.url }}" class="house-image img-fluid">
                {% endfor %}
            {% endif %}
        </div>

        

    </div>

    <div class="house-edit-footer block block-footer d-flex justify-content-center">
        {% if is_creating %}
            <input type="submit" class="btn btn-primary py-1" value="Create"/>
        {% else %}
            <input type="submit" class="btn btn-warning py-1" value="Edit"/>
        {% endif %}
    </div> <!-- house-edit-footer -->

    {% for error in errors_type %}
        {{ error }} <br/>
    {% endfor %}
</form>

templates/HouseSerch/house_page.html
{% extends "base.html" %}

{% block title %}Note {{ note.id }}{% endblock %}
{% block head %} {{ house.title }} {% endblock %}

{% block content %}

    <div class="house" id="house-element-{{ house.pk }}">
        {% if is_owner %}
            <form>
                <button type="button"
                        class="delete-element btn btn-danger ml-2" id="delete-element-{{ house.pk }}">
                    [Delete]
                </button>
                <button type="button" formaction="/house/edit/{{ house.pk }}/"
                        class="btn btn-warning ml-2" id="edit-element-{{ house.pk }}">
                    [Edit]
                </button>
            </form>
        {% endif %}

        {% if house.activity %}
            <div>Active</div>
        {% else %}
            <div>Frozen</div>
        {% endif %}

        <p> Published {{ house.date_public| date:"d-m-Y" }} </p>
        <p>Price: {{ house.price }} $ / day</p>
        <p>Owner: {{ house.owner.username }}</p>
        -------------------------

        <div class="house_img">
            {% for image in house.get_images %}
                <img src="{{ image.image.url }}" height="200" width="300"/>
            {% endfor %}
        </div>

        <div>
            <p>Type: {{ type }}</p>
            <p>Address: {{ house.country.name }}, {{ house.city }}, {{ house.address }}</p>
            <p>Rooms/sleeper place: {{ house.rooms }} / {{ house.sleeper }}</p>
            <p>{{ house.about }}</p>

        </div>
        -------------------------
    </div>


{% endblock %}


{% block script %}

    {% load staticfiles %}
    <script src="{% static '/js/js.cookie.js' %}"></script>
    <script src="{% static '/js/ajax_csrf.js' %}"></script>
    <script src="{% static '/js/house.js' %}"></script>


{% endblock %}

templates/HouseSerch/house_search.html
{% extends "base.html" %}

{% block title %}House search{% endblock %}

{% block head %}House search{% endblock %}
{% block external %}
    {% load staticfiles %}
    <!-- >jquery-ui для вывода ползунка </!-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" type="text/css" href="{% static '/css/search.css' %}">
    <script src="{% static '/js/jquery_3_3_1.min.js' %}"></script>


{% endblock %}


{% block content %}
    <!-- >Форма поиска</!-->
    {% include 'HouseSerch/multi_search_form.html' %}

    {% include 'HouseSerch/includes/paginatin_block.html' %}
    <!-- >Список домов</!-->
    {% include 'HouseSerch/includes/houses_list.html' %}

{% endblock %}

{% block script %}

    {% load staticfiles %}
    <!-- >jquery-ui для вывода ползунка </!-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript" src="{% static "js/jsearch.js" %}"></script>

    <!-- >Подгружает вписок стран для выбора </!-->
    <script type="text/javascript" src="{% static "js/ajax_load_countries.js" %}"></script>

{% endblock %}

templates/HouseSerch/limit_house.html
{% extends "base.html" %}

{% block title %}Limit| House{% endblock %}
{% block external %}

{% endblock %}

{% block head %}{{ user.username }} | House{% endblock %}

{% block content %}

    <h2>Sorry, but you can't public more that 5 house advertisement</h2>

{% endblock %}

templates/HouseSerch/multi_search_form.html
<form method="get" action="">

    {{ form_search.non_field_errors }}
    <div class="SearchForm">

        <div class="fieldWrapper">
            {{ form_search.country.errors }}
            {{ form_search.country }}
        </div>

        <datalist id="countries"></datalist>

        <div class="fieldWrapper">
            {{ form_search.city.errors }}
            {{ form_search.city }}
        </div>

        <div class="fieldWrapper">
            {{ form_search.type.errors }}
            {% for check in form_search.type %}
                <label for="{{ check.id_for_label }}">
                    {{ check.choice_label }}
                    <span class="radio">{{ check.tag }}</span>
                </label>
            {% endfor %}
        </div>

        <div class="fieldWrapper">
            {{ form_search.min_price.errors }}
            {{ form_search.max_price.errors }}
            <label for="{{ form_search.min_price.id_for_label }}">From:</label>
            {{ form_search.min_price }}
            <label for="{{ form_search.max_price.id_for_label }}">To:</label>
            {{ form_search.max_price }}
        </div>

        <div id="slider_min_max_price"></div>


        <div class="fieldWrapper">
            {{ form_search.rooms.errors }}
            <label for="{{ form_search.rooms.id_for_label }}">Rooms:</label>
            {{ form_search.rooms }}
        </div>

        <div class="fieldWrapper">
            {{ form_search.sleeper.errors }}
            <label for="{{ form_search.sleeper.id_for_label }}">Sleeper:</label>
            {{ form_search.sleeper }}
        </div>

        <div class="fieldWrapper">
            {{ form_search.active.errors }}
            <label for="{{ form_search.active.id_for_label }}">Only active:</label>
            {{ form_search.active }}
        </div>

        <div class="fieldWrapper">
            {{ form_search.public.errors }}
            <label for="{{ form_search.public.id_for_label }}">After date:</label>
            {{ form_search.public }}
        </div>

    </div>

    <input type="submit" value="Search"/>
</form>